///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace VCRanorexTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the VCRanorexTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("85d57d4d-d425-4645-85a5-4a218340d059")]
    public partial class VCRanorexTestRepository : RepoGenBaseFolder
    {
        static VCRanorexTestRepository instance = new VCRanorexTestRepository();
        VCRanorexTestRepositoryFolders.DefaultAppFolder _default;
        VCRanorexTestRepositoryFolders.OpenJobAppFolder _openjob;
        VCRanorexTestRepositoryFolders.VersionControlTestAppFolder _versioncontroltest;
        VCRanorexTestRepositoryFolders.PointsGridAppFolder _pointsgrid;
        VCRanorexTestRepositoryFolders.AddPointAppFolder _addpoint;
        VCRanorexTestRepositoryFolders.LineworkAppFolder _linework;
        VCRanorexTestRepositoryFolders.AddLineAppFolder _addline;
        VCRanorexTestRepositoryFolders.ContextMenuMfAppFolder _contextmenumf;
        VCRanorexTestRepositoryFolders.FormMapAppFolder _formmap;
        VCRanorexTestRepositoryFolders.WarningAppFolder _warning;
        VCRanorexTestRepositoryFolders.DeleteAppFolder _delete;

        /// <summary>
        /// Gets the singleton class instance representing the VCRanorexTestRepository element repository.
        /// </summary>
        [RepositoryFolder("85d57d4d-d425-4645-85a5-4a218340d059")]
        public static VCRanorexTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public VCRanorexTestRepository() 
            : base("VCRanorexTestRepository", "/", null, 0, false, "85d57d4d-d425-4645-85a5-4a218340d059", ".\\RepositoryImages\\VCRanorexTestRepository85d57d4d.rximgres")
        {
            _default = new VCRanorexTestRepositoryFolders.DefaultAppFolder(this);
            _openjob = new VCRanorexTestRepositoryFolders.OpenJobAppFolder(this);
            _versioncontroltest = new VCRanorexTestRepositoryFolders.VersionControlTestAppFolder(this);
            _pointsgrid = new VCRanorexTestRepositoryFolders.PointsGridAppFolder(this);
            _addpoint = new VCRanorexTestRepositoryFolders.AddPointAppFolder(this);
            _linework = new VCRanorexTestRepositoryFolders.LineworkAppFolder(this);
            _addline = new VCRanorexTestRepositoryFolders.AddLineAppFolder(this);
            _contextmenumf = new VCRanorexTestRepositoryFolders.ContextMenuMfAppFolder(this);
            _formmap = new VCRanorexTestRepositoryFolders.FormMapAppFolder(this);
            _warning = new VCRanorexTestRepositoryFolders.WarningAppFolder(this);
            _delete = new VCRanorexTestRepositoryFolders.DeleteAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("85d57d4d-d425-4645-85a5-4a218340d059")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Default folder.
        /// </summary>
        [RepositoryFolder("66a51060-6610-4afc-946a-8e78a3848799")]
        public virtual VCRanorexTestRepositoryFolders.DefaultAppFolder Default
        {
            get { return _default; }
        }

        /// <summary>
        /// The OpenJob folder.
        /// </summary>
        [RepositoryFolder("873f73f3-5589-4dc4-b99b-ca937e7d5b6a")]
        public virtual VCRanorexTestRepositoryFolders.OpenJobAppFolder OpenJob
        {
            get { return _openjob; }
        }

        /// <summary>
        /// The VersionControlTest folder.
        /// </summary>
        [RepositoryFolder("7f8a66c9-01cd-4ace-be23-28147320b3d9")]
        public virtual VCRanorexTestRepositoryFolders.VersionControlTestAppFolder VersionControlTest
        {
            get { return _versioncontroltest; }
        }

        /// <summary>
        /// The PointsGrid folder.
        /// </summary>
        [RepositoryFolder("b257fe91-987a-49ca-b25c-d2a85a2b1c69")]
        public virtual VCRanorexTestRepositoryFolders.PointsGridAppFolder PointsGrid
        {
            get { return _pointsgrid; }
        }

        /// <summary>
        /// The AddPoint folder.
        /// </summary>
        [RepositoryFolder("543e146e-6fb7-4b57-ba7c-2cec0034b4a9")]
        public virtual VCRanorexTestRepositoryFolders.AddPointAppFolder AddPoint
        {
            get { return _addpoint; }
        }

        /// <summary>
        /// The Linework folder.
        /// </summary>
        [RepositoryFolder("803269bb-41bb-4810-9cc3-e3e6ae5d192a")]
        public virtual VCRanorexTestRepositoryFolders.LineworkAppFolder Linework
        {
            get { return _linework; }
        }

        /// <summary>
        /// The AddLine folder.
        /// </summary>
        [RepositoryFolder("86b5c776-9ec0-4cc9-96c3-4fa1b3e86350")]
        public virtual VCRanorexTestRepositoryFolders.AddLineAppFolder AddLine
        {
            get { return _addline; }
        }

        /// <summary>
        /// The ContextMenuMf folder.
        /// </summary>
        [RepositoryFolder("eebfd5ef-bd66-4344-b897-9ace18079fe8")]
        public virtual VCRanorexTestRepositoryFolders.ContextMenuMfAppFolder ContextMenuMf
        {
            get { return _contextmenumf; }
        }

        /// <summary>
        /// The FormMap folder.
        /// </summary>
        [RepositoryFolder("860a094e-6be8-4db9-8093-25c00d189d74")]
        public virtual VCRanorexTestRepositoryFolders.FormMapAppFolder FormMap
        {
            get { return _formmap; }
        }

        /// <summary>
        /// The Warning folder.
        /// </summary>
        [RepositoryFolder("a1443fbf-76ef-485e-a6fe-18ce6e0a0a90")]
        public virtual VCRanorexTestRepositoryFolders.WarningAppFolder Warning
        {
            get { return _warning; }
        }

        /// <summary>
        /// The Delete folder.
        /// </summary>
        [RepositoryFolder("97c5a2df-196d-4101-b776-e15bbfbfefb4")]
        public virtual VCRanorexTestRepositoryFolders.DeleteAppFolder Delete
        {
            get { return _delete; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class VCRanorexTestRepositoryFolders
    {
        /// <summary>
        /// The DefaultAppFolder folder.
        /// </summary>
        [RepositoryFolder("66a51060-6610-4afc-946a-8e78a3848799")]
        public partial class DefaultAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _mainmenuselectionInfo;
            RepoItemInfo _secondarymenuselectionInfo;

            /// <summary>
            /// Creates a new Default  folder.
            /// </summary>
            public DefaultAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Default", "/form[@title='Default']", parentFolder, 30000, null, false, "66a51060-6610-4afc-946a-8e78a3848799", "")
            {
                _mainmenuselectionInfo = new RepoItemInfo(this, "MainMenuSelection", "element[@controlid='1000']", 30000, null, "b13ab02a-6627-48f0-8cd1-2f9eb2995eb0");
                _secondarymenuselectionInfo = new RepoItemInfo(this, "SecondaryMenuSelection", "?/?/element[@controlid='1000']", 30000, null, "284083db-8e30-4c8b-b9dd-71d4ebf6083d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("66a51060-6610-4afc-946a-8e78a3848799")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("66a51060-6610-4afc-946a-8e78a3848799")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MainMenuSelection item.
            /// </summary>
            [RepositoryItem("b13ab02a-6627-48f0-8cd1-2f9eb2995eb0")]
            public virtual Ranorex.Unknown MainMenuSelection
            {
                get
                {
                    return _mainmenuselectionInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The MainMenuSelection item info.
            /// </summary>
            [RepositoryItemInfo("b13ab02a-6627-48f0-8cd1-2f9eb2995eb0")]
            public virtual RepoItemInfo MainMenuSelectionInfo
            {
                get
                {
                    return _mainmenuselectionInfo;
                }
            }

            /// <summary>
            /// The SecondaryMenuSelection item.
            /// </summary>
            [RepositoryItem("284083db-8e30-4c8b-b9dd-71d4ebf6083d")]
            public virtual Ranorex.Unknown SecondaryMenuSelection
            {
                get
                {
                    return _secondarymenuselectionInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SecondaryMenuSelection item info.
            /// </summary>
            [RepositoryItemInfo("284083db-8e30-4c8b-b9dd-71d4ebf6083d")]
            public virtual RepoItemInfo SecondaryMenuSelectionInfo
            {
                get
                {
                    return _secondarymenuselectionInfo;
                }
            }
        }

        /// <summary>
        /// The OpenJobAppFolder folder.
        /// </summary>
        [RepositoryFolder("873f73f3-5589-4dc4-b99b-ca937e7d5b6a")]
        public partial class OpenJobAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _versioncontroltestInfo;
            RepoItemInfo _acceptchangesInfo;
            RepoItemInfo _defaultInfo;

            /// <summary>
            /// Creates a new OpenJob  folder.
            /// </summary>
            public OpenJobAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OpenJob", "/form[@title='Open Job']", parentFolder, 30000, null, false, "873f73f3-5589-4dc4-b99b-ca937e7d5b6a", "")
            {
                _versioncontroltestInfo = new RepoItemInfo(this, "VersionControlTest", "?/?/row[@index='0']/cell[@text='VersionControlTest']", 30000, null, "2de5a6ba-e337-4c0c-821e-fcf5db649533");
                _acceptchangesInfo = new RepoItemInfo(this, "AcceptChanges", "button[@controlid='41830']", 30000, null, "476760b8-01a3-44c8-bfdb-167d4d222b88");
                _defaultInfo = new RepoItemInfo(this, "Default", "?/?/row[@index='0']/cell[@text='Default']", 30000, null, "69a5e4a5-b68a-475b-8f37-502002548b79");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("873f73f3-5589-4dc4-b99b-ca937e7d5b6a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("873f73f3-5589-4dc4-b99b-ca937e7d5b6a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The VersionControlTest item.
            /// </summary>
            [RepositoryItem("2de5a6ba-e337-4c0c-821e-fcf5db649533")]
            public virtual Ranorex.Cell VersionControlTest
            {
                get
                {
                    return _versioncontroltestInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The VersionControlTest item info.
            /// </summary>
            [RepositoryItemInfo("2de5a6ba-e337-4c0c-821e-fcf5db649533")]
            public virtual RepoItemInfo VersionControlTestInfo
            {
                get
                {
                    return _versioncontroltestInfo;
                }
            }

            /// <summary>
            /// The AcceptChanges item.
            /// </summary>
            [RepositoryItem("476760b8-01a3-44c8-bfdb-167d4d222b88")]
            public virtual Ranorex.Button AcceptChanges
            {
                get
                {
                    return _acceptchangesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AcceptChanges item info.
            /// </summary>
            [RepositoryItemInfo("476760b8-01a3-44c8-bfdb-167d4d222b88")]
            public virtual RepoItemInfo AcceptChangesInfo
            {
                get
                {
                    return _acceptchangesInfo;
                }
            }

            /// <summary>
            /// The Default item.
            /// </summary>
            [RepositoryItem("69a5e4a5-b68a-475b-8f37-502002548b79")]
            public virtual Ranorex.Cell Default
            {
                get
                {
                    return _defaultInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Default item info.
            /// </summary>
            [RepositoryItemInfo("69a5e4a5-b68a-475b-8f37-502002548b79")]
            public virtual RepoItemInfo DefaultInfo
            {
                get
                {
                    return _defaultInfo;
                }
            }
        }

        /// <summary>
        /// The VersionControlTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("7f8a66c9-01cd-4ace-be23-28147320b3d9")]
        public partial class VersionControlTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _mainmenuselectionInfo;
            RepoItemInfo _secondarymenuselectionInfo;

            /// <summary>
            /// Creates a new VersionControlTest  folder.
            /// </summary>
            public VersionControlTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("VersionControlTest", "/form[@title='VersionControlTest']", parentFolder, 30000, null, false, "7f8a66c9-01cd-4ace-be23-28147320b3d9", "")
            {
                _mainmenuselectionInfo = new RepoItemInfo(this, "MainMenuSelection", "element[@controlid='1000']", 30000, null, "50c54255-095a-48ac-9dad-5281197783b2");
                _secondarymenuselectionInfo = new RepoItemInfo(this, "SecondaryMenuSelection", "?/?/element[@controlid='1000']", 30000, null, "93d152f9-addd-425c-a893-be8132837400");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7f8a66c9-01cd-4ace-be23-28147320b3d9")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7f8a66c9-01cd-4ace-be23-28147320b3d9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MainMenuSelection item.
            /// </summary>
            [RepositoryItem("50c54255-095a-48ac-9dad-5281197783b2")]
            public virtual Ranorex.Unknown MainMenuSelection
            {
                get
                {
                    return _mainmenuselectionInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The MainMenuSelection item info.
            /// </summary>
            [RepositoryItemInfo("50c54255-095a-48ac-9dad-5281197783b2")]
            public virtual RepoItemInfo MainMenuSelectionInfo
            {
                get
                {
                    return _mainmenuselectionInfo;
                }
            }

            /// <summary>
            /// The SecondaryMenuSelection item.
            /// </summary>
            [RepositoryItem("93d152f9-addd-425c-a893-be8132837400")]
            public virtual Ranorex.Unknown SecondaryMenuSelection
            {
                get
                {
                    return _secondarymenuselectionInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SecondaryMenuSelection item info.
            /// </summary>
            [RepositoryItemInfo("93d152f9-addd-425c-a893-be8132837400")]
            public virtual RepoItemInfo SecondaryMenuSelectionInfo
            {
                get
                {
                    return _secondarymenuselectionInfo;
                }
            }
        }

        /// <summary>
        /// The PointsGridAppFolder folder.
        /// </summary>
        [RepositoryFolder("b257fe91-987a-49ca-b25c-d2a85a2b1c69")]
        public partial class PointsGridAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addInfo;
            RepoItemInfo _homeInfo;
            RepoItemInfo _cell1Info;
            RepoItemInfo _cell5Info;
            RepoItemInfo _deleteInfo;

            /// <summary>
            /// Creates a new PointsGrid  folder.
            /// </summary>
            public PointsGridAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PointsGrid", "/form[@title='Points: Grid']", parentFolder, 30000, null, false, "b257fe91-987a-49ca-b25c-d2a85a2b1c69", "")
            {
                _addInfo = new RepoItemInfo(this, "Add", "button[@text='Add']", 30000, null, "d88a60dc-79e8-4e63-be51-2f15395b1707");
                _homeInfo = new RepoItemInfo(this, "Home", "button[@controlid='41829']", 30000, null, "6a90e17b-27b0-4bac-9d11-e74742c633b3");
                _cell1Info = new RepoItemInfo(this, "Cell1", "?/?/row[@index='0']/cell[@text='1']", 30000, null, "d35d66ed-62a3-456f-a63a-e8cd0dd1fbf6");
                _cell5Info = new RepoItemInfo(this, "Cell5", "?/?/row[@index='4']/cell[@text='5']", 30000, null, "7dc21d57-e87a-4ca8-ad44-8b35e876158c");
                _deleteInfo = new RepoItemInfo(this, "Delete", "button[@text='Delete']", 30000, null, "6cdc4fa7-19bf-4d97-829c-ab733b405e81");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b257fe91-987a-49ca-b25c-d2a85a2b1c69")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b257fe91-987a-49ca-b25c-d2a85a2b1c69")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Add item.
            /// </summary>
            [RepositoryItem("d88a60dc-79e8-4e63-be51-2f15395b1707")]
            public virtual Ranorex.Button Add
            {
                get
                {
                    return _addInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Add item info.
            /// </summary>
            [RepositoryItemInfo("d88a60dc-79e8-4e63-be51-2f15395b1707")]
            public virtual RepoItemInfo AddInfo
            {
                get
                {
                    return _addInfo;
                }
            }

            /// <summary>
            /// The Home item.
            /// </summary>
            [RepositoryItem("6a90e17b-27b0-4bac-9d11-e74742c633b3")]
            public virtual Ranorex.Button Home
            {
                get
                {
                    return _homeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Home item info.
            /// </summary>
            [RepositoryItemInfo("6a90e17b-27b0-4bac-9d11-e74742c633b3")]
            public virtual RepoItemInfo HomeInfo
            {
                get
                {
                    return _homeInfo;
                }
            }

            /// <summary>
            /// The Cell1 item.
            /// </summary>
            [RepositoryItem("d35d66ed-62a3-456f-a63a-e8cd0dd1fbf6")]
            public virtual Ranorex.Cell Cell1
            {
                get
                {
                    return _cell1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Cell1 item info.
            /// </summary>
            [RepositoryItemInfo("d35d66ed-62a3-456f-a63a-e8cd0dd1fbf6")]
            public virtual RepoItemInfo Cell1Info
            {
                get
                {
                    return _cell1Info;
                }
            }

            /// <summary>
            /// The Cell5 item.
            /// </summary>
            [RepositoryItem("7dc21d57-e87a-4ca8-ad44-8b35e876158c")]
            public virtual Ranorex.Cell Cell5
            {
                get
                {
                    return _cell5Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Cell5 item info.
            /// </summary>
            [RepositoryItemInfo("7dc21d57-e87a-4ca8-ad44-8b35e876158c")]
            public virtual RepoItemInfo Cell5Info
            {
                get
                {
                    return _cell5Info;
                }
            }

            /// <summary>
            /// The Delete item.
            /// </summary>
            [RepositoryItem("6cdc4fa7-19bf-4d97-829c-ab733b405e81")]
            public virtual Ranorex.Button Delete
            {
                get
                {
                    return _deleteInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Delete item info.
            /// </summary>
            [RepositoryItemInfo("6cdc4fa7-19bf-4d97-829c-ab733b405e81")]
            public virtual RepoItemInfo DeleteInfo
            {
                get
                {
                    return _deleteInfo;
                }
            }
        }

        /// <summary>
        /// The AddPointAppFolder folder.
        /// </summary>
        [RepositoryFolder("543e146e-6fb7-4b57-ba7c-2cec0034b4a9")]
        public partial class AddPointAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text20910Info;
            RepoItemInfo _buttonInfo;
            RepoItemInfo _text20655Info;
            RepoItemInfo _text20837Info;
            RepoItemInfo _text20726Info;

            /// <summary>
            /// Creates a new AddPoint  folder.
            /// </summary>
            public AddPointAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AddPoint", "/form[@title='Add Point']", parentFolder, 30000, null, false, "543e146e-6fb7-4b57-ba7c-2cec0034b4a9", "")
            {
                _text20910Info = new RepoItemInfo(this, "Text20910", "?/?/text[@controlid='20910']", 30000, null, "fcc7bbe6-cef2-4aad-8bcd-bbd030d12b5b");
                _buttonInfo = new RepoItemInfo(this, "Button", "button[@text='' and @controlid='1']", 30000, null, "622e5c67-d3d0-4534-b80d-1c5e9c902fcf");
                _text20655Info = new RepoItemInfo(this, "Text20655", "?/?/text[@controlid='20655']", 30000, null, "353afd09-6c96-46a2-bbc8-79f3be697044");
                _text20837Info = new RepoItemInfo(this, "Text20837", "?/?/text[@controlid='20837']", 30000, null, "1954a794-ef0d-4566-a66d-f2bf3683dc4b");
                _text20726Info = new RepoItemInfo(this, "Text20726", "?/?/text[@controlid='20726']", 30000, null, "2ccac77b-5ef5-4e4f-a6b8-8868f8492680");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("543e146e-6fb7-4b57-ba7c-2cec0034b4a9")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("543e146e-6fb7-4b57-ba7c-2cec0034b4a9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text20910 item.
            /// </summary>
            [RepositoryItem("fcc7bbe6-cef2-4aad-8bcd-bbd030d12b5b")]
            public virtual Ranorex.Text Text20910
            {
                get
                {
                    return _text20910Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text20910 item info.
            /// </summary>
            [RepositoryItemInfo("fcc7bbe6-cef2-4aad-8bcd-bbd030d12b5b")]
            public virtual RepoItemInfo Text20910Info
            {
                get
                {
                    return _text20910Info;
                }
            }

            /// <summary>
            /// The Button item.
            /// </summary>
            [RepositoryItem("622e5c67-d3d0-4534-b80d-1c5e9c902fcf")]
            public virtual Ranorex.Button Button
            {
                get
                {
                    return _buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button item info.
            /// </summary>
            [RepositoryItemInfo("622e5c67-d3d0-4534-b80d-1c5e9c902fcf")]
            public virtual RepoItemInfo ButtonInfo
            {
                get
                {
                    return _buttonInfo;
                }
            }

            /// <summary>
            /// The Text20655 item.
            /// </summary>
            [RepositoryItem("353afd09-6c96-46a2-bbc8-79f3be697044")]
            public virtual Ranorex.Text Text20655
            {
                get
                {
                    return _text20655Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text20655 item info.
            /// </summary>
            [RepositoryItemInfo("353afd09-6c96-46a2-bbc8-79f3be697044")]
            public virtual RepoItemInfo Text20655Info
            {
                get
                {
                    return _text20655Info;
                }
            }

            /// <summary>
            /// The Text20837 item.
            /// </summary>
            [RepositoryItem("1954a794-ef0d-4566-a66d-f2bf3683dc4b")]
            public virtual Ranorex.Text Text20837
            {
                get
                {
                    return _text20837Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text20837 item info.
            /// </summary>
            [RepositoryItemInfo("1954a794-ef0d-4566-a66d-f2bf3683dc4b")]
            public virtual RepoItemInfo Text20837Info
            {
                get
                {
                    return _text20837Info;
                }
            }

            /// <summary>
            /// The Text20726 item.
            /// </summary>
            [RepositoryItem("2ccac77b-5ef5-4e4f-a6b8-8868f8492680")]
            public virtual Ranorex.Text Text20726
            {
                get
                {
                    return _text20726Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text20726 item info.
            /// </summary>
            [RepositoryItemInfo("2ccac77b-5ef5-4e4f-a6b8-8868f8492680")]
            public virtual RepoItemInfo Text20726Info
            {
                get
                {
                    return _text20726Info;
                }
            }
        }

        /// <summary>
        /// The LineworkAppFolder folder.
        /// </summary>
        [RepositoryFolder("803269bb-41bb-4810-9cc3-e3e6ae5d192a")]
        public partial class LineworkAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addInfo;
            RepoItemInfo _homeInfo;
            RepoItemInfo _line1Info;
            RepoItemInfo _deleteInfo;

            /// <summary>
            /// Creates a new Linework  folder.
            /// </summary>
            public LineworkAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Linework", "/form[@title='Linework']", parentFolder, 30000, null, false, "803269bb-41bb-4810-9cc3-e3e6ae5d192a", "")
            {
                _addInfo = new RepoItemInfo(this, "Add", "button[@text='Add']", 30000, null, "4e69ba4b-9ea8-4e99-8ae5-4b6d7c62cc64");
                _homeInfo = new RepoItemInfo(this, "Home", "button[@controlid='41829']", 30000, null, "86bb4aba-b482-4f22-897c-9f5a9b366117");
                _line1Info = new RepoItemInfo(this, "Line1", "table[@controlid='20057']/?/?/cell[@text='Line-1']", 30000, null, "83901f02-e25d-4876-8f8a-68e64d19837e");
                _deleteInfo = new RepoItemInfo(this, "Delete", "button[@text='Delete']", 30000, null, "29ec6e96-2d3b-4a44-b75a-d23c7082d8b9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("803269bb-41bb-4810-9cc3-e3e6ae5d192a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("803269bb-41bb-4810-9cc3-e3e6ae5d192a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Add item.
            /// </summary>
            [RepositoryItem("4e69ba4b-9ea8-4e99-8ae5-4b6d7c62cc64")]
            public virtual Ranorex.Button Add
            {
                get
                {
                    return _addInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Add item info.
            /// </summary>
            [RepositoryItemInfo("4e69ba4b-9ea8-4e99-8ae5-4b6d7c62cc64")]
            public virtual RepoItemInfo AddInfo
            {
                get
                {
                    return _addInfo;
                }
            }

            /// <summary>
            /// The Home item.
            /// </summary>
            [RepositoryItem("86bb4aba-b482-4f22-897c-9f5a9b366117")]
            public virtual Ranorex.Button Home
            {
                get
                {
                    return _homeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Home item info.
            /// </summary>
            [RepositoryItemInfo("86bb4aba-b482-4f22-897c-9f5a9b366117")]
            public virtual RepoItemInfo HomeInfo
            {
                get
                {
                    return _homeInfo;
                }
            }

            /// <summary>
            /// The Line1 item.
            /// </summary>
            [RepositoryItem("83901f02-e25d-4876-8f8a-68e64d19837e")]
            public virtual Ranorex.Cell Line1
            {
                get
                {
                    return _line1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Line1 item info.
            /// </summary>
            [RepositoryItemInfo("83901f02-e25d-4876-8f8a-68e64d19837e")]
            public virtual RepoItemInfo Line1Info
            {
                get
                {
                    return _line1Info;
                }
            }

            /// <summary>
            /// The Delete item.
            /// </summary>
            [RepositoryItem("29ec6e96-2d3b-4a44-b75a-d23c7082d8b9")]
            public virtual Ranorex.Button Delete
            {
                get
                {
                    return _deleteInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Delete item info.
            /// </summary>
            [RepositoryItemInfo("29ec6e96-2d3b-4a44-b75a-d23c7082d8b9")]
            public virtual RepoItemInfo DeleteInfo
            {
                get
                {
                    return _deleteInfo;
                }
            }
        }

        /// <summary>
        /// The AddLineAppFolder folder.
        /// </summary>
        [RepositoryFolder("86b5c776-9ec0-4cc9-96c3-4fa1b3e86350")]
        public partial class AddLineAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addpointsInfo;
            RepoItemInfo _buttonInfo;

            /// <summary>
            /// Creates a new AddLine  folder.
            /// </summary>
            public AddLineAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AddLine", "/form[@title='Add Line']", parentFolder, 30000, null, false, "86b5c776-9ec0-4cc9-96c3-4fa1b3e86350", "")
            {
                _addpointsInfo = new RepoItemInfo(this, "AddPoints", "?/?/button[@text='Add Points']", 30000, null, "68eac7c0-b5e3-4033-b3ba-2f92d60ab3d2");
                _buttonInfo = new RepoItemInfo(this, "Button", "button[@text='' and @controlid='1']", 30000, null, "3e667ab1-efb3-47c7-b0f0-baa651d62add");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("86b5c776-9ec0-4cc9-96c3-4fa1b3e86350")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("86b5c776-9ec0-4cc9-96c3-4fa1b3e86350")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddPoints item.
            /// </summary>
            [RepositoryItem("68eac7c0-b5e3-4033-b3ba-2f92d60ab3d2")]
            public virtual Ranorex.Button AddPoints
            {
                get
                {
                    return _addpointsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AddPoints item info.
            /// </summary>
            [RepositoryItemInfo("68eac7c0-b5e3-4033-b3ba-2f92d60ab3d2")]
            public virtual RepoItemInfo AddPointsInfo
            {
                get
                {
                    return _addpointsInfo;
                }
            }

            /// <summary>
            /// The Button item.
            /// </summary>
            [RepositoryItem("3e667ab1-efb3-47c7-b0f0-baa651d62add")]
            public virtual Ranorex.Button Button
            {
                get
                {
                    return _buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button item info.
            /// </summary>
            [RepositoryItemInfo("3e667ab1-efb3-47c7-b0f0-baa651d62add")]
            public virtual RepoItemInfo ButtonInfo
            {
                get
                {
                    return _buttonInfo;
                }
            }
        }

        /// <summary>
        /// The ContextMenuMfAppFolder folder.
        /// </summary>
        [RepositoryFolder("eebfd5ef-bd66-4344-b897-9ace18079fe8")]
        public partial class ContextMenuMfAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _menuitemInfo;

            /// <summary>
            /// Creates a new ContextMenuMf  folder.
            /// </summary>
            public ContextMenuMfAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ContextMenuMf", "/contextmenu[@processname='mf']", parentFolder, 30000, null, false, "eebfd5ef-bd66-4344-b897-9ace18079fe8", "")
            {
                _menuitemInfo = new RepoItemInfo(this, "MenuItem", "contextmenu/menuitem[9]", 30000, null, "7ad5a905-ccad-4a48-a97d-048bbff91c05");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("eebfd5ef-bd66-4344-b897-9ace18079fe8")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("eebfd5ef-bd66-4344-b897-9ace18079fe8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuItem item.
            /// </summary>
            [RepositoryItem("7ad5a905-ccad-4a48-a97d-048bbff91c05")]
            public virtual Ranorex.MenuItem MenuItem
            {
                get
                {
                    return _menuitemInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItem item info.
            /// </summary>
            [RepositoryItemInfo("7ad5a905-ccad-4a48-a97d-048bbff91c05")]
            public virtual RepoItemInfo MenuItemInfo
            {
                get
                {
                    return _menuitemInfo;
                }
            }
        }

        /// <summary>
        /// The FormMapAppFolder folder.
        /// </summary>
        [RepositoryFolder("860a094e-6be8-4db9-8093-25c00d189d74")]
        public partial class FormMapAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonInfo;
            RepoItemInfo _button1Info;
            RepoItemInfo _element20063Info;
            RepoItemInfo _button2Info;

            /// <summary>
            /// Creates a new FormMap  folder.
            /// </summary>
            public FormMapAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormMap", "/form[@title='Map']", parentFolder, 30000, null, false, "860a094e-6be8-4db9-8093-25c00d189d74", "")
            {
                _buttonInfo = new RepoItemInfo(this, "Button", "element[@controlid='20063']/?/?/button[@controlid='1000']", 30000, null, "57a90b69-bcba-487f-a111-d4a7e27a4c1d");
                _button1Info = new RepoItemInfo(this, "Button1", "element[@controlid='20063']/?/?/button[@controlid='1005']", 30000, null, "7a3f72c3-177e-40a9-a9a9-26870119d670");
                _element20063Info = new RepoItemInfo(this, "Element20063", "element[@controlid='20063']", 30000, null, "a307619d-1a0a-42e5-b9c7-20cf9dea5aeb");
                _button2Info = new RepoItemInfo(this, "Button2", "button[@controlid='1']", 30000, null, "1daeecd1-5b43-434a-94c8-180b74fec4c6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("860a094e-6be8-4db9-8093-25c00d189d74")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("860a094e-6be8-4db9-8093-25c00d189d74")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Button item.
            /// </summary>
            [RepositoryItem("57a90b69-bcba-487f-a111-d4a7e27a4c1d")]
            public virtual Ranorex.Button Button
            {
                get
                {
                    return _buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button item info.
            /// </summary>
            [RepositoryItemInfo("57a90b69-bcba-487f-a111-d4a7e27a4c1d")]
            public virtual RepoItemInfo ButtonInfo
            {
                get
                {
                    return _buttonInfo;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("7a3f72c3-177e-40a9-a9a9-26870119d670")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("7a3f72c3-177e-40a9-a9a9-26870119d670")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }

            /// <summary>
            /// The Element20063 item.
            /// </summary>
            [RepositoryItem("a307619d-1a0a-42e5-b9c7-20cf9dea5aeb")]
            public virtual Ranorex.Unknown Element20063
            {
                get
                {
                    return _element20063Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element20063 item info.
            /// </summary>
            [RepositoryItemInfo("a307619d-1a0a-42e5-b9c7-20cf9dea5aeb")]
            public virtual RepoItemInfo Element20063Info
            {
                get
                {
                    return _element20063Info;
                }
            }

            /// <summary>
            /// The Button2 item.
            /// </summary>
            [RepositoryItem("1daeecd1-5b43-434a-94c8-180b74fec4c6")]
            public virtual Ranorex.Button Button2
            {
                get
                {
                    return _button2Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button2 item info.
            /// </summary>
            [RepositoryItemInfo("1daeecd1-5b43-434a-94c8-180b74fec4c6")]
            public virtual RepoItemInfo Button2Info
            {
                get
                {
                    return _button2Info;
                }
            }
        }

        /// <summary>
        /// The WarningAppFolder folder.
        /// </summary>
        [RepositoryFolder("a1443fbf-76ef-485e-a6fe-18ce6e0a0a90")]
        public partial class WarningAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _yesInfo;

            /// <summary>
            /// Creates a new Warning  folder.
            /// </summary>
            public WarningAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Warning", "/form[@title='Warning']", parentFolder, 30000, null, false, "a1443fbf-76ef-485e-a6fe-18ce6e0a0a90", "")
            {
                _yesInfo = new RepoItemInfo(this, "Yes", "button[@text='Yes']", 30000, null, "24132ccf-6c14-4edb-83d0-4ca48cc9cdad");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a1443fbf-76ef-485e-a6fe-18ce6e0a0a90")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a1443fbf-76ef-485e-a6fe-18ce6e0a0a90")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Yes item.
            /// </summary>
            [RepositoryItem("24132ccf-6c14-4edb-83d0-4ca48cc9cdad")]
            public virtual Ranorex.Button Yes
            {
                get
                {
                    return _yesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Yes item info.
            /// </summary>
            [RepositoryItemInfo("24132ccf-6c14-4edb-83d0-4ca48cc9cdad")]
            public virtual RepoItemInfo YesInfo
            {
                get
                {
                    return _yesInfo;
                }
            }
        }

        /// <summary>
        /// The DeleteAppFolder folder.
        /// </summary>
        [RepositoryFolder("97c5a2df-196d-4101-b776-e15bbfbfefb4")]
        public partial class DeleteAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _yesInfo;

            /// <summary>
            /// Creates a new Delete  folder.
            /// </summary>
            public DeleteAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Delete", "/form[@title='Delete']", parentFolder, 30000, null, false, "97c5a2df-196d-4101-b776-e15bbfbfefb4", "")
            {
                _yesInfo = new RepoItemInfo(this, "Yes", "button[@text='Yes']", 30000, null, "9779eb99-f206-433c-a6bf-625c5dc2e3a9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("97c5a2df-196d-4101-b776-e15bbfbfefb4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("97c5a2df-196d-4101-b776-e15bbfbfefb4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Yes item.
            /// </summary>
            [RepositoryItem("9779eb99-f206-433c-a6bf-625c5dc2e3a9")]
            public virtual Ranorex.Button Yes
            {
                get
                {
                    return _yesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Yes item info.
            /// </summary>
            [RepositoryItemInfo("9779eb99-f206-433c-a6bf-625c5dc2e3a9")]
            public virtual RepoItemInfo YesInfo
            {
                get
                {
                    return _yesInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
