///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace VCRanorexTest.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddPoints recording.
    /// </summary>
    [TestModule("42de8c5e-5653-4dcb-a92d-0366fe5f8d10", ModuleType.Recording, 1)]
    public partial class AddPoints : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::VCRanorexTest.VCRanorexTestRepository repository.
        /// </summary>
        public static global::VCRanorexTest.VCRanorexTestRepository repo = global::VCRanorexTest.VCRanorexTestRepository.Instance;

        static AddPoints instance = new AddPoints();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddPoints()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddPoints Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VersionControlTest.MainMenuSelection' at 603;146.", repo.VersionControlTest.MainMenuSelectionInfo, new RecordItemIndex(0));
            repo.VersionControlTest.MainMenuSelection.Click("603;146");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VersionControlTest.SecondaryMenuSelection' at 95;144.", repo.VersionControlTest.SecondaryMenuSelectionInfo, new RecordItemIndex(1));
            repo.VersionControlTest.SecondaryMenuSelection.Click("95;144");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'PointsGrid.Add'.", repo.PointsGrid.AddInfo, new RecordItemIndex(2));
            repo.PointsGrid.Add.Press();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'AddPoint.PointName' at 203;27.", repo.AddPoint.PointNameInfo, new RecordItemIndex(3));
            repo.AddPoint.PointName.DoubleClick("203;27");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'AddPoint.PointName'.", repo.AddPoint.PointNameInfo, new RecordItemIndex(4));
            repo.AddPoint.PointName.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddPoint.AcceptChanges' at 33;28.", repo.AddPoint.AcceptChangesInfo, new RecordItemIndex(5));
            repo.AddPoint.AcceptChanges.Click("33;28");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'PointsGrid.Add'.", repo.PointsGrid.AddInfo, new RecordItemIndex(6));
            repo.PointsGrid.Add.Press();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'AddPoint.NorthValue' at 112;20.", repo.AddPoint.NorthValueInfo, new RecordItemIndex(7));
            repo.AddPoint.NorthValue.DoubleClick("112;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '-100' with focus on 'AddPoint.NorthValue'.", repo.AddPoint.NorthValueInfo, new RecordItemIndex(8));
            repo.AddPoint.NorthValue.PressKeys("-100");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'AddPoint.EastValue' at 101;19.", repo.AddPoint.EastValueInfo, new RecordItemIndex(9));
            repo.AddPoint.EastValue.DoubleClick("101;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '-100' with focus on 'AddPoint.EastValue'.", repo.AddPoint.EastValueInfo, new RecordItemIndex(10));
            repo.AddPoint.EastValue.PressKeys("-100");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddPoint.EllipsoidalHt' at 143;23.", repo.AddPoint.EllipsoidalHtInfo, new RecordItemIndex(11));
            repo.AddPoint.EllipsoidalHt.Click("143;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddPoint.AcceptChanges' at 31;22.", repo.AddPoint.AcceptChangesInfo, new RecordItemIndex(12));
            repo.AddPoint.AcceptChanges.Click("31;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'PointsGrid.Add'.", repo.PointsGrid.AddInfo, new RecordItemIndex(13));
            repo.PointsGrid.Add.Press();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'AddPoint.NorthValue' at 169;22.", repo.AddPoint.NorthValueInfo, new RecordItemIndex(14));
            repo.AddPoint.NorthValue.DoubleClick("169;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{Back}100' with focus on 'AddPoint.NorthValue'.", repo.AddPoint.NorthValueInfo, new RecordItemIndex(15));
            repo.AddPoint.NorthValue.PressKeys("{Back}{Back}100");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddPoint.AcceptChanges' at 31;27.", repo.AddPoint.AcceptChangesInfo, new RecordItemIndex(16));
            repo.AddPoint.AcceptChanges.Click("31;27");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'PointsGrid.Add'.", repo.PointsGrid.AddInfo, new RecordItemIndex(17));
            repo.PointsGrid.Add.Press();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'AddPoint.EastValue' at 157;21.", repo.AddPoint.EastValueInfo, new RecordItemIndex(18));
            repo.AddPoint.EastValue.DoubleClick("157;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{Back}100' with focus on 'AddPoint.EastValue'.", repo.AddPoint.EastValueInfo, new RecordItemIndex(19));
            repo.AddPoint.EastValue.PressKeys("{Back}{Back}100");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddPoint.AcceptChanges' at 33;35.", repo.AddPoint.AcceptChangesInfo, new RecordItemIndex(20));
            repo.AddPoint.AcceptChanges.Click("33;35");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'PointsGrid.Add'.", repo.PointsGrid.AddInfo, new RecordItemIndex(21));
            repo.PointsGrid.Add.Press();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'AddPoint.NorthValue' at 172;24.", repo.AddPoint.NorthValueInfo, new RecordItemIndex(22));
            repo.AddPoint.NorthValue.DoubleClick("172;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{Back}-100' with focus on 'AddPoint.NorthValue'.", repo.AddPoint.NorthValueInfo, new RecordItemIndex(23));
            repo.AddPoint.NorthValue.PressKeys("{Back}{Back}-100");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddPoint.AcceptChanges' at 18;23.", repo.AddPoint.AcceptChangesInfo, new RecordItemIndex(24));
            repo.AddPoint.AcceptChanges.Click("18;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'PointsGrid.Home'.", repo.PointsGrid.HomeInfo, new RecordItemIndex(25));
            repo.PointsGrid.Home.Press();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
