///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace VCRanorexTest.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VC_Teardown recording.
    /// </summary>
    [TestModule("3fdb97b0-14b5-471b-9475-aaeec3857733", ModuleType.Recording, 1)]
    public partial class VC_Teardown : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::VCRanorexTest.VCRanorexTestRepository repository.
        /// </summary>
        public static global::VCRanorexTest.VCRanorexTestRepository repo = global::VCRanorexTest.VCRanorexTestRepository.Instance;

        static VC_Teardown instance = new VC_Teardown();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VC_Teardown()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VC_Teardown Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Start of routine
            Report.Log(ReportLevel.Info, "Section", "Start of routine", new RecordItemIndex(0));
            
            // Force close job from any window
            Report.Log(ReportLevel.Info, "Section", "Force close job from any window", new RecordItemIndex(1));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(2));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'VersionControlTest'.", repo.VersionControlTest.SelfInfo, new RecordItemIndex(3));
            Host.Current.CloseApplication(repo.VersionControlTest.Self, new Duration(0));
            Delay.Milliseconds(0);
            
            // Delay and open job - It should open on the main menu
            Report.Log(ReportLevel.Info, "Section", "Delay and open job - It should open on the main menu", new RecordItemIndex(4));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(5));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Program Files\\MAGNET Field PC\\mf.exe' in normal mode.", new RecordItemIndex(6));
            Host.Local.RunApplication("C:\\Program Files\\MAGNET Field PC\\mf.exe", "", "C:\\Program Files\\MAGNET Field PC", false);
            Delay.Milliseconds(0);
            
            // Remove Linework
            Report.Log(ReportLevel.Info, "Section", "Remove Linework", new RecordItemIndex(7));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VersionControlTest.MainMenuSelection' at 598;145.", repo.VersionControlTest.MainMenuSelectionInfo, new RecordItemIndex(8));
            repo.VersionControlTest.MainMenuSelection.Click("598;145");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VersionControlTest.SecondaryMenuSelection' at 598;145.", repo.VersionControlTest.SecondaryMenuSelectionInfo, new RecordItemIndex(9));
            repo.VersionControlTest.SecondaryMenuSelection.Click("598;145");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Linework.Line1' at 34;26.", repo.Linework.Line1Info, new RecordItemIndex(10));
            repo.Linework.Line1.Click("34;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Linework.Delete' at 97;37.", repo.Linework.DeleteInfo, new RecordItemIndex(11));
            repo.Linework.Delete.Click("97;37");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Delete.Yes' at 95;33.", repo.Delete.YesInfo, new RecordItemIndex(12));
            repo.Delete.Yes.Click("95;33");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Linework.Home' at 37;31.", repo.Linework.HomeInfo, new RecordItemIndex(13));
            repo.Linework.Home.Click("37;31");
            Delay.Milliseconds(0);
            
            // Remove Points
            Report.Log(ReportLevel.Info, "Section", "Remove Points", new RecordItemIndex(14));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VersionControlTest.MainMenuSelection' at 598;151.", repo.VersionControlTest.MainMenuSelectionInfo, new RecordItemIndex(15));
            repo.VersionControlTest.MainMenuSelection.Click("598;151");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VersionControlTest.SecondaryMenuSelection' at 87;148.", repo.VersionControlTest.SecondaryMenuSelectionInfo, new RecordItemIndex(16));
            repo.VersionControlTest.SecondaryMenuSelection.Click("87;148");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PointsGrid.Cell1' at 63;31.", repo.PointsGrid.Cell1Info, new RecordItemIndex(17));
            repo.PointsGrid.Cell1.Click("63;31");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}' with focus on 'PointsGrid'.", repo.PointsGrid.SelfInfo, new RecordItemIndex(18));
            repo.PointsGrid.Self.EnsureVisible();
            Keyboard.Press("{LShiftKey down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PointsGrid.Cell5' at 63;29.", repo.PointsGrid.Cell5Info, new RecordItemIndex(19));
            repo.PointsGrid.Cell5.Click("63;29");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey up}' with focus on 'PointsGrid'.", repo.PointsGrid.SelfInfo, new RecordItemIndex(20));
            repo.PointsGrid.Self.EnsureVisible();
            Keyboard.Press("{LShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PointsGrid.Delete' at 66;36.", repo.PointsGrid.DeleteInfo, new RecordItemIndex(21));
            repo.PointsGrid.Delete.Click("66;36");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Warning.Yes' at 91;33.", repo.Warning.YesInfo, new RecordItemIndex(22));
            repo.Warning.Yes.Click("91;33");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PointsGrid.Home' at 36;31.", repo.PointsGrid.HomeInfo, new RecordItemIndex(23));
            repo.PointsGrid.Home.Click("36;31");
            Delay.Milliseconds(0);
            
            // Open Default Application
            Report.Log(ReportLevel.Info, "Section", "Open Default Application", new RecordItemIndex(24));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VersionControlTest.MainMenuSelection' at 93;147.", repo.VersionControlTest.MainMenuSelectionInfo, new RecordItemIndex(25));
            repo.VersionControlTest.MainMenuSelection.Click("93;147");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VersionControlTest.SecondaryMenuSelection' at 259;139.", repo.VersionControlTest.SecondaryMenuSelectionInfo, new RecordItemIndex(26));
            repo.VersionControlTest.SecondaryMenuSelection.Click("259;139");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OpenJob.Default' at 89;23.", repo.OpenJob.DefaultInfo, new RecordItemIndex(27));
            repo.OpenJob.Default.Click("89;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OpenJob.AcceptChanges' at 36;30.", repo.OpenJob.AcceptChangesInfo, new RecordItemIndex(28));
            repo.OpenJob.AcceptChanges.Click("36;30");
            Delay.Milliseconds(0);
            
            // Close Field after opening Default job
            Report.Log(ReportLevel.Info, "Section", "Close Field after opening Default job", new RecordItemIndex(29));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(30));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'Default'.", repo.Default.SelfInfo, new RecordItemIndex(31));
            Host.Current.CloseApplication(repo.Default.Self, new Duration(0));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
